name: My Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "Fuse"
          replace: "fuse"
          regex: false
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
